[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.isort]
include_trailing_comma = true
combine_as_imports = true
force_sort_within_sections = true
known_third_party = ["probnum"]