name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  formatting:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'formatting-requirements.txt'
      - name: Install formatting dependencies
        id: fmt-deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check code style with `black`
        run: black --check --diff .
      - name: Check import order with `isort`
        run: isort --check --diff .
        if: success() || steps.fmt-deps.outcome == 'success'
