# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Release

on:
  release:
    types: [created]

jobs:
  deploy-pypi:
    name: Deploy to PyPI

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install build and deploy dependencies
        run: pip install --upgrade build twine
      - name: Build `linpde-gp` wheel
        run: python -m build
      - name: Deploy wheel to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/*py3-none-any.whl
